 
use_frameworks!
source 'https://cdn.cocoapods.org/'
platform :ios, '11.0'
target 'SwiftPageView_Example' do
  pod 'SwiftPageView', :path => '../'

  pod 'JXPageControl'
  pod 'Kingfisher'
  pod 'SnapKit'
end
